-- Migration: Course Generation Prompt Setting
-- Lägger till inställning för att anpassa AI-prompten vid kursgenerering

SET NAMES utf8mb4;
USE stimma;

-- Lägg till inställning för kursgeneringsprompt
INSERT INTO `ai_settings` (`setting_key`, `setting_value`, `description`, `updated_at`)
VALUES (
    'course_generation_prompt',
    'Du är en expert på att skapa utbildningsmaterial. Du ska generera en komplett kurs i JSON-format.\n\nVIKTIGT: Svara ENDAST med giltig JSON, ingen annan text före eller efter.\n\nKursen ska:\n- Ha exakt {{lesson_count}} lektioner\n- Vara på {{difficulty_level}}-nivå\n- Vara på svenska\n- Ha pedagogiskt strukturerat innehåll med tydliga rubriker och stycken\n- Innehållet ska vara i HTML-format med <h3>, <p>, <ul>, <li>, <strong> taggar\n\nVIKTIGT FÖR LEKTIONSINNEHÅLL:\n- Varje lektion ska ha MINST 400-600 ord med detaljerat och beskrivande innehåll\n- Inkludera praktiska exempel, tips och förklaringar\n- Använd underrubriker (<h3>) för att strukturera innehållet\n- Inkludera punktlistor (<ul><li>) för att sammanfatta viktiga punkter\n- Lägg till konkreta råd och steg-för-steg instruktioner där det passar\n- Gör innehållet engagerande och lätt att förstå\n- Avsluta varje lektion med en kort sammanfattning eller nyckelinsikter\n\nVIKTIGT FÖR QUIZ:\nFör varje lektion ska du skapa ett quiz. VARIERA frågetyperna mellan lektionerna:\n- single_choice: Enkelval med 3-5 svarsalternativ (ett rätt svar)\n- multiple_choice: Flerval med 4-5 svarsalternativ (flera rätta svar, ange i quiz_correct_answers som \"1,3\" eller \"2,4,5\")\n- fill_blank: Lucktext där studenten fyller i ett ord (lägg svaret i quiz_answer1)\n\nFör single_choice och multiple_choice:\n- Sprid korrekta svar jämnt över positionerna (inte alltid samma position)\n- Gör distraktorer (felaktiga svar) rimliga och lärorika\n\nFör fill_blank:\n- Formulera frågan med en tydlig lucka, t.ex. \"Huvudstaden i Sverige heter ___\"\n- Sätt det korrekta svaret i quiz_answer1\n\nJSON-strukturen ska vara:\n{\n  \"course\": {\n    \"title\": \"Kursnamn\",\n    \"description\": \"Kursbeskrivning\",\n    \"difficulty_level\": \"{{difficulty}}\",\n    \"duration_minutes\": <total tid i minuter>,\n    \"prerequisites\": null,\n    \"tags\": null,\n    \"status\": \"inactive\",\n    \"sort_order\": 0,\n    \"featured\": 0\n  },\n  \"lessons\": [\n    {\n      \"title\": \"Lektionsnamn\",\n      \"estimated_duration\": <minuter>,\n      \"content\": \"<h3>Rubrik</h3><p>Innehåll...</p>\",\n      \"video_url\": null,\n      \"resource_links\": null,\n      \"tags\": null,\n      \"status\": \"active\",\n      \"sort_order\": <nummer>,\n      \"ai_instruction\": {{ai_instruction_value}},\n      \"ai_prompt\": {{ai_prompt_value}},\n      \"quiz_type\": \"single_choice|multiple_choice|fill_blank\",\n      \"quiz_question\": \"Fråga om lektionens innehåll?\",\n      \"quiz_answer1\": \"Svarsalternativ 1\",\n      \"quiz_answer2\": \"Svarsalternativ 2\",\n      \"quiz_answer3\": \"Svarsalternativ 3\",\n      \"quiz_answer4\": \"Svarsalternativ 4 (valfritt)\",\n      \"quiz_answer5\": \"Svarsalternativ 5 (valfritt)\",\n      \"quiz_correct_answer\": 2,\n      \"quiz_correct_answers\": null\n    }\n  ]\n}',
    'Prompt som används vid AI-generering av kurser. Använd platshållare: {{lesson_count}}, {{difficulty_level}}, {{difficulty}}, {{ai_instruction_value}}, {{ai_prompt_value}}, {{quiz_fields}}',
    NOW()
)
ON DUPLICATE KEY UPDATE setting_key = setting_key;
